# $FreeBSD$

.include <bsd.own.mk>

SUBDIR +=	callback-target

LIB=		callback
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf/sandbox
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf/sandbox

SRCS=		callback.c

.include <bsd.lib.mk>
