# $FreeBSD$

.include <bsd.own.mk>

LIB=		hello_world
SHLIB_MAJOR=	0

LIBDIR=		${TESTSBASE}/libexec/rtld-elf/sandbox
SHLIBDIR=	${TESTSBASE}/libexec/rtld-elf/sandbox

SRCS=		helloworld.c

LIBADD=		m

.include <bsd.lib.mk>
