# $FreeBSD$

TESTSDIR=	${TESTSBASE}/libexec/rtld-elf/sandbox

SUBDIR+=	libcallback \
			libdo-raw-syscall \
			libhelloworld \
			libhelloworld-with-deps \
			libprints \
			sandbox-target

ATF_TESTS_C+=	dependency-policies

.include <bsd.test.mk>
