# $FreeBSD$

TESTSDIR=	${TESTSBASE}/libexec/rtld-elf/sandbox

SUBDIR+=	libhelloworld libhelloworld-with-deps libprints libdo-raw-syscall sandbox-target

ATF_TESTS_C+=	dependency-policies

.include <bsd.test.mk>
